services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - "5781:8080"
    restart: unless-stopped
    volumes:
      - open-webui:/app/backend/data
      - ./.env:/app/backend/.env:ro

  nginx-cors-proxy:
    image: nginx:alpine
    ports:
      - "8281:80"
    volumes:
      - ./nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped

  inserther:
    build:
      context: ./inserther
      dockerfile: DOCKERFILE
    restart: unless-stopped
    volumes:
      - ./inserther/.env:/app/.env:ro

volumes:
  open-webui:
